services:
  app:
    container_name: myproject
    image: myproject-test
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - KAKAO_REDIRECT_URI=${KAKAO_REDIRECT_URI}
      - KAKAO_FRONTEND_REDIRECT_URI=${KAKAO_FRONTEND_REDIRECT_URI}
      - ACCESS_EXPIRATION=${ACCESS_EXPIRATION}
      - REFRESH_EXPIRATION=${REFRESH_EXPIRATION}
      - SPRING_DATA_REDIS_HOST=${SPRING_DATA_REDIS_HOST}
  redis:
    image: redis:6.2
    container_name: redis-project
    restart: always
    ports:
      - "6379:6379"

