name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        run: ./gradlew build

      - name: Copy Jar to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: 54.116.13.185
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 키
          source: "build/libs/*.jar"
          target: "~/spring-app"

      - name: Run Spring boot app on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 54.116.13.185
          username: ubuntu
          key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 키
          script:
            pkill -f 'java -jar' || true

#      # Docker build & Push
#      - name: Docker build & push to Docker hub
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-test .
#          docker push ${{ secrets.DOCKER_USERNAME }}/docker-test
#
#      # EC2 배포
#      - name: Docker image pull & Deploy to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }} # EC2 인스턴스 퍼블릭 DNS
#          username: ubuntu
#          key: ${{ secrets.EC2_PRIVATE_KEY }} # pem 키
#          # 도커 작업
#          script: |
#            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-test:latest
#            sudo docker stop $(sudo docker ps -a -q)
#            sudo docker run -d --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/docker-test:latest
#            sudo docker rm $(sudo docker ps --filter 'status=exited' -a -q)
#            sudo docker image prune -a -f
